# Generated by Django 3.1 on 2020-09-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_blog', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
