# Generated by Django 3.1 on 2020-09-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_blog', '0005_comment_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='author',
        ),
    ]
